/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/config/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConfigurationRecorderStatus_s implements ConfigurationRecorderStatus_Interface
type FakeConfigurationRecorderStatus_s struct {
	Fake *FakeConfigV1alpha1
	ns   string
}

var configurationrecorderstatus_sResource = schema.GroupVersionResource{Group: "config.aws.kubeform.com", Version: "v1alpha1", Resource: "configurationrecorderstatus_s"}

var configurationrecorderstatus_sKind = schema.GroupVersionKind{Group: "config.aws.kubeform.com", Version: "v1alpha1", Kind: "ConfigurationRecorderStatus_"}

// Get takes name of the configurationRecorderStatus_, and returns the corresponding configurationRecorderStatus_ object, and an error if there is any.
func (c *FakeConfigurationRecorderStatus_s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConfigurationRecorderStatus_, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(configurationrecorderstatus_sResource, c.ns, name), &v1alpha1.ConfigurationRecorderStatus_{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigurationRecorderStatus_), err
}

// List takes label and field selectors, and returns the list of ConfigurationRecorderStatus_s that match those selectors.
func (c *FakeConfigurationRecorderStatus_s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConfigurationRecorderStatus_List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(configurationrecorderstatus_sResource, configurationrecorderstatus_sKind, c.ns, opts), &v1alpha1.ConfigurationRecorderStatus_List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConfigurationRecorderStatus_List{ListMeta: obj.(*v1alpha1.ConfigurationRecorderStatus_List).ListMeta}
	for _, item := range obj.(*v1alpha1.ConfigurationRecorderStatus_List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested configurationRecorderStatus_s.
func (c *FakeConfigurationRecorderStatus_s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(configurationrecorderstatus_sResource, c.ns, opts))

}

// Create takes the representation of a configurationRecorderStatus_ and creates it.  Returns the server's representation of the configurationRecorderStatus_, and an error, if there is any.
func (c *FakeConfigurationRecorderStatus_s) Create(ctx context.Context, configurationRecorderStatus_ *v1alpha1.ConfigurationRecorderStatus_, opts v1.CreateOptions) (result *v1alpha1.ConfigurationRecorderStatus_, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(configurationrecorderstatus_sResource, c.ns, configurationRecorderStatus_), &v1alpha1.ConfigurationRecorderStatus_{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigurationRecorderStatus_), err
}

// Update takes the representation of a configurationRecorderStatus_ and updates it. Returns the server's representation of the configurationRecorderStatus_, and an error, if there is any.
func (c *FakeConfigurationRecorderStatus_s) Update(ctx context.Context, configurationRecorderStatus_ *v1alpha1.ConfigurationRecorderStatus_, opts v1.UpdateOptions) (result *v1alpha1.ConfigurationRecorderStatus_, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(configurationrecorderstatus_sResource, c.ns, configurationRecorderStatus_), &v1alpha1.ConfigurationRecorderStatus_{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigurationRecorderStatus_), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConfigurationRecorderStatus_s) UpdateStatus(ctx context.Context, configurationRecorderStatus_ *v1alpha1.ConfigurationRecorderStatus_, opts v1.UpdateOptions) (*v1alpha1.ConfigurationRecorderStatus_, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(configurationrecorderstatus_sResource, "status", c.ns, configurationRecorderStatus_), &v1alpha1.ConfigurationRecorderStatus_{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigurationRecorderStatus_), err
}

// Delete takes name of the configurationRecorderStatus_ and deletes it. Returns an error if one occurs.
func (c *FakeConfigurationRecorderStatus_s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(configurationrecorderstatus_sResource, c.ns, name), &v1alpha1.ConfigurationRecorderStatus_{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConfigurationRecorderStatus_s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(configurationrecorderstatus_sResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConfigurationRecorderStatus_List{})
	return err
}

// Patch applies the patch and returns the patched configurationRecorderStatus_.
func (c *FakeConfigurationRecorderStatus_s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConfigurationRecorderStatus_, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(configurationrecorderstatus_sResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConfigurationRecorderStatus_{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigurationRecorderStatus_), err
}
