/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/config/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAggregateAuthorizations implements AggregateAuthorizationInterface
type FakeAggregateAuthorizations struct {
	Fake *FakeConfigV1alpha1
	ns   string
}

var aggregateauthorizationsResource = schema.GroupVersionResource{Group: "config.aws.kubeform.com", Version: "v1alpha1", Resource: "aggregateauthorizations"}

var aggregateauthorizationsKind = schema.GroupVersionKind{Group: "config.aws.kubeform.com", Version: "v1alpha1", Kind: "AggregateAuthorization"}

// Get takes name of the aggregateAuthorization, and returns the corresponding aggregateAuthorization object, and an error if there is any.
func (c *FakeAggregateAuthorizations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AggregateAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(aggregateauthorizationsResource, c.ns, name), &v1alpha1.AggregateAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregateAuthorization), err
}

// List takes label and field selectors, and returns the list of AggregateAuthorizations that match those selectors.
func (c *FakeAggregateAuthorizations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AggregateAuthorizationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(aggregateauthorizationsResource, aggregateauthorizationsKind, c.ns, opts), &v1alpha1.AggregateAuthorizationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AggregateAuthorizationList{ListMeta: obj.(*v1alpha1.AggregateAuthorizationList).ListMeta}
	for _, item := range obj.(*v1alpha1.AggregateAuthorizationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aggregateAuthorizations.
func (c *FakeAggregateAuthorizations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(aggregateauthorizationsResource, c.ns, opts))

}

// Create takes the representation of a aggregateAuthorization and creates it.  Returns the server's representation of the aggregateAuthorization, and an error, if there is any.
func (c *FakeAggregateAuthorizations) Create(ctx context.Context, aggregateAuthorization *v1alpha1.AggregateAuthorization, opts v1.CreateOptions) (result *v1alpha1.AggregateAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(aggregateauthorizationsResource, c.ns, aggregateAuthorization), &v1alpha1.AggregateAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregateAuthorization), err
}

// Update takes the representation of a aggregateAuthorization and updates it. Returns the server's representation of the aggregateAuthorization, and an error, if there is any.
func (c *FakeAggregateAuthorizations) Update(ctx context.Context, aggregateAuthorization *v1alpha1.AggregateAuthorization, opts v1.UpdateOptions) (result *v1alpha1.AggregateAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(aggregateauthorizationsResource, c.ns, aggregateAuthorization), &v1alpha1.AggregateAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregateAuthorization), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAggregateAuthorizations) UpdateStatus(ctx context.Context, aggregateAuthorization *v1alpha1.AggregateAuthorization, opts v1.UpdateOptions) (*v1alpha1.AggregateAuthorization, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(aggregateauthorizationsResource, "status", c.ns, aggregateAuthorization), &v1alpha1.AggregateAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregateAuthorization), err
}

// Delete takes name of the aggregateAuthorization and deletes it. Returns an error if one occurs.
func (c *FakeAggregateAuthorizations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(aggregateauthorizationsResource, c.ns, name), &v1alpha1.AggregateAuthorization{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAggregateAuthorizations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(aggregateauthorizationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AggregateAuthorizationList{})
	return err
}

// Patch applies the patch and returns the patched aggregateAuthorization.
func (c *FakeAggregateAuthorizations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AggregateAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aggregateauthorizationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AggregateAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AggregateAuthorization), err
}
