/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/dx/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePrivateVirtualInterfaces implements PrivateVirtualInterfaceInterface
type FakePrivateVirtualInterfaces struct {
	Fake *FakeDxV1alpha1
	ns   string
}

var privatevirtualinterfacesResource = schema.GroupVersionResource{Group: "dx.aws.kubeform.com", Version: "v1alpha1", Resource: "privatevirtualinterfaces"}

var privatevirtualinterfacesKind = schema.GroupVersionKind{Group: "dx.aws.kubeform.com", Version: "v1alpha1", Kind: "PrivateVirtualInterface"}

// Get takes name of the privateVirtualInterface, and returns the corresponding privateVirtualInterface object, and an error if there is any.
func (c *FakePrivateVirtualInterfaces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PrivateVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(privatevirtualinterfacesResource, c.ns, name), &v1alpha1.PrivateVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateVirtualInterface), err
}

// List takes label and field selectors, and returns the list of PrivateVirtualInterfaces that match those selectors.
func (c *FakePrivateVirtualInterfaces) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrivateVirtualInterfaceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(privatevirtualinterfacesResource, privatevirtualinterfacesKind, c.ns, opts), &v1alpha1.PrivateVirtualInterfaceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PrivateVirtualInterfaceList{ListMeta: obj.(*v1alpha1.PrivateVirtualInterfaceList).ListMeta}
	for _, item := range obj.(*v1alpha1.PrivateVirtualInterfaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested privateVirtualInterfaces.
func (c *FakePrivateVirtualInterfaces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(privatevirtualinterfacesResource, c.ns, opts))

}

// Create takes the representation of a privateVirtualInterface and creates it.  Returns the server's representation of the privateVirtualInterface, and an error, if there is any.
func (c *FakePrivateVirtualInterfaces) Create(ctx context.Context, privateVirtualInterface *v1alpha1.PrivateVirtualInterface, opts v1.CreateOptions) (result *v1alpha1.PrivateVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(privatevirtualinterfacesResource, c.ns, privateVirtualInterface), &v1alpha1.PrivateVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateVirtualInterface), err
}

// Update takes the representation of a privateVirtualInterface and updates it. Returns the server's representation of the privateVirtualInterface, and an error, if there is any.
func (c *FakePrivateVirtualInterfaces) Update(ctx context.Context, privateVirtualInterface *v1alpha1.PrivateVirtualInterface, opts v1.UpdateOptions) (result *v1alpha1.PrivateVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(privatevirtualinterfacesResource, c.ns, privateVirtualInterface), &v1alpha1.PrivateVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateVirtualInterface), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePrivateVirtualInterfaces) UpdateStatus(ctx context.Context, privateVirtualInterface *v1alpha1.PrivateVirtualInterface, opts v1.UpdateOptions) (*v1alpha1.PrivateVirtualInterface, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(privatevirtualinterfacesResource, "status", c.ns, privateVirtualInterface), &v1alpha1.PrivateVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateVirtualInterface), err
}

// Delete takes name of the privateVirtualInterface and deletes it. Returns an error if one occurs.
func (c *FakePrivateVirtualInterfaces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(privatevirtualinterfacesResource, c.ns, name), &v1alpha1.PrivateVirtualInterface{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePrivateVirtualInterfaces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(privatevirtualinterfacesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PrivateVirtualInterfaceList{})
	return err
}

// Patch applies the patch and returns the patched privateVirtualInterface.
func (c *FakePrivateVirtualInterfaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PrivateVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(privatevirtualinterfacesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PrivateVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateVirtualInterface), err
}
