/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/dx/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTransitVirtualInterfaces implements TransitVirtualInterfaceInterface
type FakeTransitVirtualInterfaces struct {
	Fake *FakeDxV1alpha1
	ns   string
}

var transitvirtualinterfacesResource = schema.GroupVersionResource{Group: "dx.aws.kubeform.com", Version: "v1alpha1", Resource: "transitvirtualinterfaces"}

var transitvirtualinterfacesKind = schema.GroupVersionKind{Group: "dx.aws.kubeform.com", Version: "v1alpha1", Kind: "TransitVirtualInterface"}

// Get takes name of the transitVirtualInterface, and returns the corresponding transitVirtualInterface object, and an error if there is any.
func (c *FakeTransitVirtualInterfaces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TransitVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(transitvirtualinterfacesResource, c.ns, name), &v1alpha1.TransitVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitVirtualInterface), err
}

// List takes label and field selectors, and returns the list of TransitVirtualInterfaces that match those selectors.
func (c *FakeTransitVirtualInterfaces) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TransitVirtualInterfaceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(transitvirtualinterfacesResource, transitvirtualinterfacesKind, c.ns, opts), &v1alpha1.TransitVirtualInterfaceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TransitVirtualInterfaceList{ListMeta: obj.(*v1alpha1.TransitVirtualInterfaceList).ListMeta}
	for _, item := range obj.(*v1alpha1.TransitVirtualInterfaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested transitVirtualInterfaces.
func (c *FakeTransitVirtualInterfaces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(transitvirtualinterfacesResource, c.ns, opts))

}

// Create takes the representation of a transitVirtualInterface and creates it.  Returns the server's representation of the transitVirtualInterface, and an error, if there is any.
func (c *FakeTransitVirtualInterfaces) Create(ctx context.Context, transitVirtualInterface *v1alpha1.TransitVirtualInterface, opts v1.CreateOptions) (result *v1alpha1.TransitVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(transitvirtualinterfacesResource, c.ns, transitVirtualInterface), &v1alpha1.TransitVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitVirtualInterface), err
}

// Update takes the representation of a transitVirtualInterface and updates it. Returns the server's representation of the transitVirtualInterface, and an error, if there is any.
func (c *FakeTransitVirtualInterfaces) Update(ctx context.Context, transitVirtualInterface *v1alpha1.TransitVirtualInterface, opts v1.UpdateOptions) (result *v1alpha1.TransitVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(transitvirtualinterfacesResource, c.ns, transitVirtualInterface), &v1alpha1.TransitVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitVirtualInterface), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTransitVirtualInterfaces) UpdateStatus(ctx context.Context, transitVirtualInterface *v1alpha1.TransitVirtualInterface, opts v1.UpdateOptions) (*v1alpha1.TransitVirtualInterface, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(transitvirtualinterfacesResource, "status", c.ns, transitVirtualInterface), &v1alpha1.TransitVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitVirtualInterface), err
}

// Delete takes name of the transitVirtualInterface and deletes it. Returns an error if one occurs.
func (c *FakeTransitVirtualInterfaces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(transitvirtualinterfacesResource, c.ns, name), &v1alpha1.TransitVirtualInterface{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTransitVirtualInterfaces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(transitvirtualinterfacesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TransitVirtualInterfaceList{})
	return err
}

// Patch applies the patch and returns the patched transitVirtualInterface.
func (c *FakeTransitVirtualInterfaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TransitVirtualInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(transitvirtualinterfacesResource, c.ns, name, pt, data, subresources...), &v1alpha1.TransitVirtualInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitVirtualInterface), err
}
