/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AccessPointPolicyListerExpansion allows custom methods to be added to
// AccessPointPolicyLister.
type AccessPointPolicyListerExpansion interface{}

// AccessPointPolicyNamespaceListerExpansion allows custom methods to be added to
// AccessPointPolicyNamespaceLister.
type AccessPointPolicyNamespaceListerExpansion interface{}

// BucketListerExpansion allows custom methods to be added to
// BucketLister.
type BucketListerExpansion interface{}

// BucketNamespaceListerExpansion allows custom methods to be added to
// BucketNamespaceLister.
type BucketNamespaceListerExpansion interface{}

// BucketLifecycleConfigurationListerExpansion allows custom methods to be added to
// BucketLifecycleConfigurationLister.
type BucketLifecycleConfigurationListerExpansion interface{}

// BucketLifecycleConfigurationNamespaceListerExpansion allows custom methods to be added to
// BucketLifecycleConfigurationNamespaceLister.
type BucketLifecycleConfigurationNamespaceListerExpansion interface{}

// BucketPolicyListerExpansion allows custom methods to be added to
// BucketPolicyLister.
type BucketPolicyListerExpansion interface{}

// BucketPolicyNamespaceListerExpansion allows custom methods to be added to
// BucketPolicyNamespaceLister.
type BucketPolicyNamespaceListerExpansion interface{}

// MultiRegionAccessPointListerExpansion allows custom methods to be added to
// MultiRegionAccessPointLister.
type MultiRegionAccessPointListerExpansion interface{}

// MultiRegionAccessPointNamespaceListerExpansion allows custom methods to be added to
// MultiRegionAccessPointNamespaceLister.
type MultiRegionAccessPointNamespaceListerExpansion interface{}

// MultiRegionAccessPointPolicyListerExpansion allows custom methods to be added to
// MultiRegionAccessPointPolicyLister.
type MultiRegionAccessPointPolicyListerExpansion interface{}

// MultiRegionAccessPointPolicyNamespaceListerExpansion allows custom methods to be added to
// MultiRegionAccessPointPolicyNamespaceLister.
type MultiRegionAccessPointPolicyNamespaceListerExpansion interface{}

// ObjectLambdaAccessPointListerExpansion allows custom methods to be added to
// ObjectLambdaAccessPointLister.
type ObjectLambdaAccessPointListerExpansion interface{}

// ObjectLambdaAccessPointNamespaceListerExpansion allows custom methods to be added to
// ObjectLambdaAccessPointNamespaceLister.
type ObjectLambdaAccessPointNamespaceListerExpansion interface{}

// ObjectLambdaAccessPointPolicyListerExpansion allows custom methods to be added to
// ObjectLambdaAccessPointPolicyLister.
type ObjectLambdaAccessPointPolicyListerExpansion interface{}

// ObjectLambdaAccessPointPolicyNamespaceListerExpansion allows custom methods to be added to
// ObjectLambdaAccessPointPolicyNamespaceLister.
type ObjectLambdaAccessPointPolicyNamespaceListerExpansion interface{}
