/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubeform.dev/provider-aws-api/apis/appsync/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GraphqlAPILister helps list GraphqlAPIs.
// All objects returned here must be treated as read-only.
type GraphqlAPILister interface {
	// List lists all GraphqlAPIs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GraphqlAPI, err error)
	// GraphqlAPIs returns an object that can list and get GraphqlAPIs.
	GraphqlAPIs(namespace string) GraphqlAPINamespaceLister
	GraphqlAPIListerExpansion
}

// graphqlAPILister implements the GraphqlAPILister interface.
type graphqlAPILister struct {
	indexer cache.Indexer
}

// NewGraphqlAPILister returns a new GraphqlAPILister.
func NewGraphqlAPILister(indexer cache.Indexer) GraphqlAPILister {
	return &graphqlAPILister{indexer: indexer}
}

// List lists all GraphqlAPIs in the indexer.
func (s *graphqlAPILister) List(selector labels.Selector) (ret []*v1alpha1.GraphqlAPI, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GraphqlAPI))
	})
	return ret, err
}

// GraphqlAPIs returns an object that can list and get GraphqlAPIs.
func (s *graphqlAPILister) GraphqlAPIs(namespace string) GraphqlAPINamespaceLister {
	return graphqlAPINamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GraphqlAPINamespaceLister helps list and get GraphqlAPIs.
// All objects returned here must be treated as read-only.
type GraphqlAPINamespaceLister interface {
	// List lists all GraphqlAPIs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GraphqlAPI, err error)
	// Get retrieves the GraphqlAPI from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.GraphqlAPI, error)
	GraphqlAPINamespaceListerExpansion
}

// graphqlAPINamespaceLister implements the GraphqlAPINamespaceLister
// interface.
type graphqlAPINamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GraphqlAPIs in the indexer for a given namespace.
func (s graphqlAPINamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.GraphqlAPI, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GraphqlAPI))
	})
	return ret, err
}

// Get retrieves the GraphqlAPI from the indexer for a given namespace and name.
func (s graphqlAPINamespaceLister) Get(name string) (*v1alpha1.GraphqlAPI, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("graphqlapi"), name)
	}
	return obj.(*v1alpha1.GraphqlAPI), nil
}
