/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/cloud9/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnvironmentMemberships implements EnvironmentMembershipInterface
type FakeEnvironmentMemberships struct {
	Fake *FakeCloud9V1alpha1
	ns   string
}

var environmentmembershipsResource = schema.GroupVersionResource{Group: "cloud9.aws.kubeform.com", Version: "v1alpha1", Resource: "environmentmemberships"}

var environmentmembershipsKind = schema.GroupVersionKind{Group: "cloud9.aws.kubeform.com", Version: "v1alpha1", Kind: "EnvironmentMembership"}

// Get takes name of the environmentMembership, and returns the corresponding environmentMembership object, and an error if there is any.
func (c *FakeEnvironmentMemberships) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EnvironmentMembership, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(environmentmembershipsResource, c.ns, name), &v1alpha1.EnvironmentMembership{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentMembership), err
}

// List takes label and field selectors, and returns the list of EnvironmentMemberships that match those selectors.
func (c *FakeEnvironmentMemberships) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EnvironmentMembershipList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(environmentmembershipsResource, environmentmembershipsKind, c.ns, opts), &v1alpha1.EnvironmentMembershipList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EnvironmentMembershipList{ListMeta: obj.(*v1alpha1.EnvironmentMembershipList).ListMeta}
	for _, item := range obj.(*v1alpha1.EnvironmentMembershipList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested environmentMemberships.
func (c *FakeEnvironmentMemberships) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(environmentmembershipsResource, c.ns, opts))

}

// Create takes the representation of a environmentMembership and creates it.  Returns the server's representation of the environmentMembership, and an error, if there is any.
func (c *FakeEnvironmentMemberships) Create(ctx context.Context, environmentMembership *v1alpha1.EnvironmentMembership, opts v1.CreateOptions) (result *v1alpha1.EnvironmentMembership, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(environmentmembershipsResource, c.ns, environmentMembership), &v1alpha1.EnvironmentMembership{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentMembership), err
}

// Update takes the representation of a environmentMembership and updates it. Returns the server's representation of the environmentMembership, and an error, if there is any.
func (c *FakeEnvironmentMemberships) Update(ctx context.Context, environmentMembership *v1alpha1.EnvironmentMembership, opts v1.UpdateOptions) (result *v1alpha1.EnvironmentMembership, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(environmentmembershipsResource, c.ns, environmentMembership), &v1alpha1.EnvironmentMembership{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentMembership), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEnvironmentMemberships) UpdateStatus(ctx context.Context, environmentMembership *v1alpha1.EnvironmentMembership, opts v1.UpdateOptions) (*v1alpha1.EnvironmentMembership, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(environmentmembershipsResource, "status", c.ns, environmentMembership), &v1alpha1.EnvironmentMembership{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentMembership), err
}

// Delete takes name of the environmentMembership and deletes it. Returns an error if one occurs.
func (c *FakeEnvironmentMemberships) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(environmentmembershipsResource, c.ns, name), &v1alpha1.EnvironmentMembership{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnvironmentMemberships) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(environmentmembershipsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EnvironmentMembershipList{})
	return err
}

// Patch applies the patch and returns the patched environmentMembership.
func (c *FakeEnvironmentMemberships) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EnvironmentMembership, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(environmentmembershipsResource, c.ns, name, pt, data, subresources...), &v1alpha1.EnvironmentMembership{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvironmentMembership), err
}
