/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	codecommitv1alpha1 "kubeform.dev/provider-aws-api/apis/codecommit/v1alpha1"
	versioned "kubeform.dev/provider-aws-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-aws-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-aws-api/client/listers/codecommit/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApprovalRuleTemplateAssociationInformer provides access to a shared informer and lister for
// ApprovalRuleTemplateAssociations.
type ApprovalRuleTemplateAssociationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ApprovalRuleTemplateAssociationLister
}

type approvalRuleTemplateAssociationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewApprovalRuleTemplateAssociationInformer constructs a new informer for ApprovalRuleTemplateAssociation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApprovalRuleTemplateAssociationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApprovalRuleTemplateAssociationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredApprovalRuleTemplateAssociationInformer constructs a new informer for ApprovalRuleTemplateAssociation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApprovalRuleTemplateAssociationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CodecommitV1alpha1().ApprovalRuleTemplateAssociations(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CodecommitV1alpha1().ApprovalRuleTemplateAssociations(namespace).Watch(context.TODO(), options)
			},
		},
		&codecommitv1alpha1.ApprovalRuleTemplateAssociation{},
		resyncPeriod,
		indexers,
	)
}

func (f *approvalRuleTemplateAssociationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApprovalRuleTemplateAssociationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *approvalRuleTemplateAssociationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&codecommitv1alpha1.ApprovalRuleTemplateAssociation{}, f.defaultInformer)
}

func (f *approvalRuleTemplateAssociationInformer) Lister() v1alpha1.ApprovalRuleTemplateAssociationLister {
	return v1alpha1.NewApprovalRuleTemplateAssociationLister(f.Informer().GetIndexer())
}
