/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-aws-api/apis/macie/v1alpha1"
)

// FakeS3BucketAssociations implements S3BucketAssociationInterface
type FakeS3BucketAssociations struct {
	Fake *FakeMacieV1alpha1
	ns   string
}

var s3bucketassociationsResource = schema.GroupVersionResource{Group: "macie.aws.kubeform.com", Version: "v1alpha1", Resource: "s3bucketassociations"}

var s3bucketassociationsKind = schema.GroupVersionKind{Group: "macie.aws.kubeform.com", Version: "v1alpha1", Kind: "S3BucketAssociation"}

// Get takes name of the s3BucketAssociation, and returns the corresponding s3BucketAssociation object, and an error if there is any.
func (c *FakeS3BucketAssociations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.S3BucketAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(s3bucketassociationsResource, c.ns, name), &v1alpha1.S3BucketAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3BucketAssociation), err
}

// List takes label and field selectors, and returns the list of S3BucketAssociations that match those selectors.
func (c *FakeS3BucketAssociations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.S3BucketAssociationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(s3bucketassociationsResource, s3bucketassociationsKind, c.ns, opts), &v1alpha1.S3BucketAssociationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.S3BucketAssociationList{ListMeta: obj.(*v1alpha1.S3BucketAssociationList).ListMeta}
	for _, item := range obj.(*v1alpha1.S3BucketAssociationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested s3BucketAssociations.
func (c *FakeS3BucketAssociations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(s3bucketassociationsResource, c.ns, opts))

}

// Create takes the representation of a s3BucketAssociation and creates it.  Returns the server's representation of the s3BucketAssociation, and an error, if there is any.
func (c *FakeS3BucketAssociations) Create(ctx context.Context, s3BucketAssociation *v1alpha1.S3BucketAssociation, opts v1.CreateOptions) (result *v1alpha1.S3BucketAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(s3bucketassociationsResource, c.ns, s3BucketAssociation), &v1alpha1.S3BucketAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3BucketAssociation), err
}

// Update takes the representation of a s3BucketAssociation and updates it. Returns the server's representation of the s3BucketAssociation, and an error, if there is any.
func (c *FakeS3BucketAssociations) Update(ctx context.Context, s3BucketAssociation *v1alpha1.S3BucketAssociation, opts v1.UpdateOptions) (result *v1alpha1.S3BucketAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(s3bucketassociationsResource, c.ns, s3BucketAssociation), &v1alpha1.S3BucketAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3BucketAssociation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeS3BucketAssociations) UpdateStatus(ctx context.Context, s3BucketAssociation *v1alpha1.S3BucketAssociation, opts v1.UpdateOptions) (*v1alpha1.S3BucketAssociation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(s3bucketassociationsResource, "status", c.ns, s3BucketAssociation), &v1alpha1.S3BucketAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3BucketAssociation), err
}

// Delete takes name of the s3BucketAssociation and deletes it. Returns an error if one occurs.
func (c *FakeS3BucketAssociations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(s3bucketassociationsResource, c.ns, name), &v1alpha1.S3BucketAssociation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeS3BucketAssociations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(s3bucketassociationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.S3BucketAssociationList{})
	return err
}

// Patch applies the patch and returns the patched s3BucketAssociation.
func (c *FakeS3BucketAssociations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.S3BucketAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(s3bucketassociationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.S3BucketAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3BucketAssociation), err
}
