/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/wafregional/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWebACLs implements WebACLInterface
type FakeWebACLs struct {
	Fake *FakeWafregionalV1alpha1
	ns   string
}

var webaclsResource = schema.GroupVersionResource{Group: "wafregional.aws.kubeform.com", Version: "v1alpha1", Resource: "webacls"}

var webaclsKind = schema.GroupVersionKind{Group: "wafregional.aws.kubeform.com", Version: "v1alpha1", Kind: "WebACL"}

// Get takes name of the webACL, and returns the corresponding webACL object, and an error if there is any.
func (c *FakeWebACLs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WebACL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(webaclsResource, c.ns, name), &v1alpha1.WebACL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebACL), err
}

// List takes label and field selectors, and returns the list of WebACLs that match those selectors.
func (c *FakeWebACLs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WebACLList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(webaclsResource, webaclsKind, c.ns, opts), &v1alpha1.WebACLList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WebACLList{ListMeta: obj.(*v1alpha1.WebACLList).ListMeta}
	for _, item := range obj.(*v1alpha1.WebACLList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested webACLs.
func (c *FakeWebACLs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(webaclsResource, c.ns, opts))

}

// Create takes the representation of a webACL and creates it.  Returns the server's representation of the webACL, and an error, if there is any.
func (c *FakeWebACLs) Create(ctx context.Context, webACL *v1alpha1.WebACL, opts v1.CreateOptions) (result *v1alpha1.WebACL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(webaclsResource, c.ns, webACL), &v1alpha1.WebACL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebACL), err
}

// Update takes the representation of a webACL and updates it. Returns the server's representation of the webACL, and an error, if there is any.
func (c *FakeWebACLs) Update(ctx context.Context, webACL *v1alpha1.WebACL, opts v1.UpdateOptions) (result *v1alpha1.WebACL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(webaclsResource, c.ns, webACL), &v1alpha1.WebACL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebACL), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWebACLs) UpdateStatus(ctx context.Context, webACL *v1alpha1.WebACL, opts v1.UpdateOptions) (*v1alpha1.WebACL, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(webaclsResource, "status", c.ns, webACL), &v1alpha1.WebACL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebACL), err
}

// Delete takes name of the webACL and deletes it. Returns an error if one occurs.
func (c *FakeWebACLs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(webaclsResource, c.ns, name), &v1alpha1.WebACL{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWebACLs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(webaclsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WebACLList{})
	return err
}

// Patch applies the patch and returns the patched webACL.
func (c *FakeWebACLs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WebACL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(webaclsResource, c.ns, name, pt, data, subresources...), &v1alpha1.WebACL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WebACL), err
}
