/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BudgetResourceAssociationListerExpansion allows custom methods to be added to
// BudgetResourceAssociationLister.
type BudgetResourceAssociationListerExpansion interface{}

// BudgetResourceAssociationNamespaceListerExpansion allows custom methods to be added to
// BudgetResourceAssociationNamespaceLister.
type BudgetResourceAssociationNamespaceListerExpansion interface{}

// ConstraintListerExpansion allows custom methods to be added to
// ConstraintLister.
type ConstraintListerExpansion interface{}

// ConstraintNamespaceListerExpansion allows custom methods to be added to
// ConstraintNamespaceLister.
type ConstraintNamespaceListerExpansion interface{}

// OrganizationsAccessListerExpansion allows custom methods to be added to
// OrganizationsAccessLister.
type OrganizationsAccessListerExpansion interface{}

// OrganizationsAccessNamespaceListerExpansion allows custom methods to be added to
// OrganizationsAccessNamespaceLister.
type OrganizationsAccessNamespaceListerExpansion interface{}

// PortfolioListerExpansion allows custom methods to be added to
// PortfolioLister.
type PortfolioListerExpansion interface{}

// PortfolioNamespaceListerExpansion allows custom methods to be added to
// PortfolioNamespaceLister.
type PortfolioNamespaceListerExpansion interface{}

// PortfolioShareListerExpansion allows custom methods to be added to
// PortfolioShareLister.
type PortfolioShareListerExpansion interface{}

// PortfolioShareNamespaceListerExpansion allows custom methods to be added to
// PortfolioShareNamespaceLister.
type PortfolioShareNamespaceListerExpansion interface{}

// PrincipalPortfolioAssociationListerExpansion allows custom methods to be added to
// PrincipalPortfolioAssociationLister.
type PrincipalPortfolioAssociationListerExpansion interface{}

// PrincipalPortfolioAssociationNamespaceListerExpansion allows custom methods to be added to
// PrincipalPortfolioAssociationNamespaceLister.
type PrincipalPortfolioAssociationNamespaceListerExpansion interface{}

// ProductListerExpansion allows custom methods to be added to
// ProductLister.
type ProductListerExpansion interface{}

// ProductNamespaceListerExpansion allows custom methods to be added to
// ProductNamespaceLister.
type ProductNamespaceListerExpansion interface{}

// ProductPortfolioAssociationListerExpansion allows custom methods to be added to
// ProductPortfolioAssociationLister.
type ProductPortfolioAssociationListerExpansion interface{}

// ProductPortfolioAssociationNamespaceListerExpansion allows custom methods to be added to
// ProductPortfolioAssociationNamespaceLister.
type ProductPortfolioAssociationNamespaceListerExpansion interface{}

// ProvisioningArtifactListerExpansion allows custom methods to be added to
// ProvisioningArtifactLister.
type ProvisioningArtifactListerExpansion interface{}

// ProvisioningArtifactNamespaceListerExpansion allows custom methods to be added to
// ProvisioningArtifactNamespaceLister.
type ProvisioningArtifactNamespaceListerExpansion interface{}

// ServiceActionListerExpansion allows custom methods to be added to
// ServiceActionLister.
type ServiceActionListerExpansion interface{}

// ServiceActionNamespaceListerExpansion allows custom methods to be added to
// ServiceActionNamespaceLister.
type ServiceActionNamespaceListerExpansion interface{}

// TagOptionListerExpansion allows custom methods to be added to
// TagOptionLister.
type TagOptionListerExpansion interface{}

// TagOptionNamespaceListerExpansion allows custom methods to be added to
// TagOptionNamespaceLister.
type TagOptionNamespaceListerExpansion interface{}

// TagOptionResourceAssociationListerExpansion allows custom methods to be added to
// TagOptionResourceAssociationLister.
type TagOptionResourceAssociationListerExpansion interface{}

// TagOptionResourceAssociationNamespaceListerExpansion allows custom methods to be added to
// TagOptionResourceAssociationNamespaceLister.
type TagOptionResourceAssociationNamespaceListerExpansion interface{}
