/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/fsx/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWindowsFileSystems implements WindowsFileSystemInterface
type FakeWindowsFileSystems struct {
	Fake *FakeFsxV1alpha1
	ns   string
}

var windowsfilesystemsResource = schema.GroupVersionResource{Group: "fsx.aws.kubeform.com", Version: "v1alpha1", Resource: "windowsfilesystems"}

var windowsfilesystemsKind = schema.GroupVersionKind{Group: "fsx.aws.kubeform.com", Version: "v1alpha1", Kind: "WindowsFileSystem"}

// Get takes name of the windowsFileSystem, and returns the corresponding windowsFileSystem object, and an error if there is any.
func (c *FakeWindowsFileSystems) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WindowsFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(windowsfilesystemsResource, c.ns, name), &v1alpha1.WindowsFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WindowsFileSystem), err
}

// List takes label and field selectors, and returns the list of WindowsFileSystems that match those selectors.
func (c *FakeWindowsFileSystems) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WindowsFileSystemList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(windowsfilesystemsResource, windowsfilesystemsKind, c.ns, opts), &v1alpha1.WindowsFileSystemList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WindowsFileSystemList{ListMeta: obj.(*v1alpha1.WindowsFileSystemList).ListMeta}
	for _, item := range obj.(*v1alpha1.WindowsFileSystemList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested windowsFileSystems.
func (c *FakeWindowsFileSystems) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(windowsfilesystemsResource, c.ns, opts))

}

// Create takes the representation of a windowsFileSystem and creates it.  Returns the server's representation of the windowsFileSystem, and an error, if there is any.
func (c *FakeWindowsFileSystems) Create(ctx context.Context, windowsFileSystem *v1alpha1.WindowsFileSystem, opts v1.CreateOptions) (result *v1alpha1.WindowsFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(windowsfilesystemsResource, c.ns, windowsFileSystem), &v1alpha1.WindowsFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WindowsFileSystem), err
}

// Update takes the representation of a windowsFileSystem and updates it. Returns the server's representation of the windowsFileSystem, and an error, if there is any.
func (c *FakeWindowsFileSystems) Update(ctx context.Context, windowsFileSystem *v1alpha1.WindowsFileSystem, opts v1.UpdateOptions) (result *v1alpha1.WindowsFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(windowsfilesystemsResource, c.ns, windowsFileSystem), &v1alpha1.WindowsFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WindowsFileSystem), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWindowsFileSystems) UpdateStatus(ctx context.Context, windowsFileSystem *v1alpha1.WindowsFileSystem, opts v1.UpdateOptions) (*v1alpha1.WindowsFileSystem, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(windowsfilesystemsResource, "status", c.ns, windowsFileSystem), &v1alpha1.WindowsFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WindowsFileSystem), err
}

// Delete takes name of the windowsFileSystem and deletes it. Returns an error if one occurs.
func (c *FakeWindowsFileSystems) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(windowsfilesystemsResource, c.ns, name), &v1alpha1.WindowsFileSystem{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWindowsFileSystems) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(windowsfilesystemsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WindowsFileSystemList{})
	return err
}

// Patch applies the patch and returns the patched windowsFileSystem.
func (c *FakeWindowsFileSystems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WindowsFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(windowsfilesystemsResource, c.ns, name, pt, data, subresources...), &v1alpha1.WindowsFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WindowsFileSystem), err
}
