/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/fsx/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOntapFileSystems implements OntapFileSystemInterface
type FakeOntapFileSystems struct {
	Fake *FakeFsxV1alpha1
	ns   string
}

var ontapfilesystemsResource = schema.GroupVersionResource{Group: "fsx.aws.kubeform.com", Version: "v1alpha1", Resource: "ontapfilesystems"}

var ontapfilesystemsKind = schema.GroupVersionKind{Group: "fsx.aws.kubeform.com", Version: "v1alpha1", Kind: "OntapFileSystem"}

// Get takes name of the ontapFileSystem, and returns the corresponding ontapFileSystem object, and an error if there is any.
func (c *FakeOntapFileSystems) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OntapFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ontapfilesystemsResource, c.ns, name), &v1alpha1.OntapFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OntapFileSystem), err
}

// List takes label and field selectors, and returns the list of OntapFileSystems that match those selectors.
func (c *FakeOntapFileSystems) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OntapFileSystemList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ontapfilesystemsResource, ontapfilesystemsKind, c.ns, opts), &v1alpha1.OntapFileSystemList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OntapFileSystemList{ListMeta: obj.(*v1alpha1.OntapFileSystemList).ListMeta}
	for _, item := range obj.(*v1alpha1.OntapFileSystemList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ontapFileSystems.
func (c *FakeOntapFileSystems) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ontapfilesystemsResource, c.ns, opts))

}

// Create takes the representation of a ontapFileSystem and creates it.  Returns the server's representation of the ontapFileSystem, and an error, if there is any.
func (c *FakeOntapFileSystems) Create(ctx context.Context, ontapFileSystem *v1alpha1.OntapFileSystem, opts v1.CreateOptions) (result *v1alpha1.OntapFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ontapfilesystemsResource, c.ns, ontapFileSystem), &v1alpha1.OntapFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OntapFileSystem), err
}

// Update takes the representation of a ontapFileSystem and updates it. Returns the server's representation of the ontapFileSystem, and an error, if there is any.
func (c *FakeOntapFileSystems) Update(ctx context.Context, ontapFileSystem *v1alpha1.OntapFileSystem, opts v1.UpdateOptions) (result *v1alpha1.OntapFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ontapfilesystemsResource, c.ns, ontapFileSystem), &v1alpha1.OntapFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OntapFileSystem), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOntapFileSystems) UpdateStatus(ctx context.Context, ontapFileSystem *v1alpha1.OntapFileSystem, opts v1.UpdateOptions) (*v1alpha1.OntapFileSystem, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ontapfilesystemsResource, "status", c.ns, ontapFileSystem), &v1alpha1.OntapFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OntapFileSystem), err
}

// Delete takes name of the ontapFileSystem and deletes it. Returns an error if one occurs.
func (c *FakeOntapFileSystems) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ontapfilesystemsResource, c.ns, name), &v1alpha1.OntapFileSystem{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOntapFileSystems) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ontapfilesystemsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OntapFileSystemList{})
	return err
}

// Patch applies the patch and returns the patched ontapFileSystem.
func (c *FakeOntapFileSystems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OntapFileSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ontapfilesystemsResource, c.ns, name, pt, data, subresources...), &v1alpha1.OntapFileSystem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OntapFileSystem), err
}
