/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/snapshot/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCreateVolumePermissions implements CreateVolumePermissionInterface
type FakeCreateVolumePermissions struct {
	Fake *FakeSnapshotV1alpha1
	ns   string
}

var createvolumepermissionsResource = schema.GroupVersionResource{Group: "snapshot.aws.kubeform.com", Version: "v1alpha1", Resource: "createvolumepermissions"}

var createvolumepermissionsKind = schema.GroupVersionKind{Group: "snapshot.aws.kubeform.com", Version: "v1alpha1", Kind: "CreateVolumePermission"}

// Get takes name of the createVolumePermission, and returns the corresponding createVolumePermission object, and an error if there is any.
func (c *FakeCreateVolumePermissions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CreateVolumePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(createvolumepermissionsResource, c.ns, name), &v1alpha1.CreateVolumePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CreateVolumePermission), err
}

// List takes label and field selectors, and returns the list of CreateVolumePermissions that match those selectors.
func (c *FakeCreateVolumePermissions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CreateVolumePermissionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(createvolumepermissionsResource, createvolumepermissionsKind, c.ns, opts), &v1alpha1.CreateVolumePermissionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CreateVolumePermissionList{ListMeta: obj.(*v1alpha1.CreateVolumePermissionList).ListMeta}
	for _, item := range obj.(*v1alpha1.CreateVolumePermissionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested createVolumePermissions.
func (c *FakeCreateVolumePermissions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(createvolumepermissionsResource, c.ns, opts))

}

// Create takes the representation of a createVolumePermission and creates it.  Returns the server's representation of the createVolumePermission, and an error, if there is any.
func (c *FakeCreateVolumePermissions) Create(ctx context.Context, createVolumePermission *v1alpha1.CreateVolumePermission, opts v1.CreateOptions) (result *v1alpha1.CreateVolumePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(createvolumepermissionsResource, c.ns, createVolumePermission), &v1alpha1.CreateVolumePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CreateVolumePermission), err
}

// Update takes the representation of a createVolumePermission and updates it. Returns the server's representation of the createVolumePermission, and an error, if there is any.
func (c *FakeCreateVolumePermissions) Update(ctx context.Context, createVolumePermission *v1alpha1.CreateVolumePermission, opts v1.UpdateOptions) (result *v1alpha1.CreateVolumePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(createvolumepermissionsResource, c.ns, createVolumePermission), &v1alpha1.CreateVolumePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CreateVolumePermission), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCreateVolumePermissions) UpdateStatus(ctx context.Context, createVolumePermission *v1alpha1.CreateVolumePermission, opts v1.UpdateOptions) (*v1alpha1.CreateVolumePermission, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(createvolumepermissionsResource, "status", c.ns, createVolumePermission), &v1alpha1.CreateVolumePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CreateVolumePermission), err
}

// Delete takes name of the createVolumePermission and deletes it. Returns an error if one occurs.
func (c *FakeCreateVolumePermissions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(createvolumepermissionsResource, c.ns, name), &v1alpha1.CreateVolumePermission{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCreateVolumePermissions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(createvolumepermissionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CreateVolumePermissionList{})
	return err
}

// Patch applies the patch and returns the patched createVolumePermission.
func (c *FakeCreateVolumePermissions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CreateVolumePermission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(createvolumepermissionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CreateVolumePermission{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CreateVolumePermission), err
}
