/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-aws-api/apis/opsworks/v1alpha1"
)

// FakePhpAppLayers implements PhpAppLayerInterface
type FakePhpAppLayers struct {
	Fake *FakeOpsworksV1alpha1
	ns   string
}

var phpapplayersResource = schema.GroupVersionResource{Group: "opsworks.aws.kubeform.com", Version: "v1alpha1", Resource: "phpapplayers"}

var phpapplayersKind = schema.GroupVersionKind{Group: "opsworks.aws.kubeform.com", Version: "v1alpha1", Kind: "PhpAppLayer"}

// Get takes name of the phpAppLayer, and returns the corresponding phpAppLayer object, and an error if there is any.
func (c *FakePhpAppLayers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PhpAppLayer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(phpapplayersResource, c.ns, name), &v1alpha1.PhpAppLayer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PhpAppLayer), err
}

// List takes label and field selectors, and returns the list of PhpAppLayers that match those selectors.
func (c *FakePhpAppLayers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PhpAppLayerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(phpapplayersResource, phpapplayersKind, c.ns, opts), &v1alpha1.PhpAppLayerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PhpAppLayerList{ListMeta: obj.(*v1alpha1.PhpAppLayerList).ListMeta}
	for _, item := range obj.(*v1alpha1.PhpAppLayerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested phpAppLayers.
func (c *FakePhpAppLayers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(phpapplayersResource, c.ns, opts))

}

// Create takes the representation of a phpAppLayer and creates it.  Returns the server's representation of the phpAppLayer, and an error, if there is any.
func (c *FakePhpAppLayers) Create(ctx context.Context, phpAppLayer *v1alpha1.PhpAppLayer, opts v1.CreateOptions) (result *v1alpha1.PhpAppLayer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(phpapplayersResource, c.ns, phpAppLayer), &v1alpha1.PhpAppLayer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PhpAppLayer), err
}

// Update takes the representation of a phpAppLayer and updates it. Returns the server's representation of the phpAppLayer, and an error, if there is any.
func (c *FakePhpAppLayers) Update(ctx context.Context, phpAppLayer *v1alpha1.PhpAppLayer, opts v1.UpdateOptions) (result *v1alpha1.PhpAppLayer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(phpapplayersResource, c.ns, phpAppLayer), &v1alpha1.PhpAppLayer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PhpAppLayer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePhpAppLayers) UpdateStatus(ctx context.Context, phpAppLayer *v1alpha1.PhpAppLayer, opts v1.UpdateOptions) (*v1alpha1.PhpAppLayer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(phpapplayersResource, "status", c.ns, phpAppLayer), &v1alpha1.PhpAppLayer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PhpAppLayer), err
}

// Delete takes name of the phpAppLayer and deletes it. Returns an error if one occurs.
func (c *FakePhpAppLayers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(phpapplayersResource, c.ns, name), &v1alpha1.PhpAppLayer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePhpAppLayers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(phpapplayersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PhpAppLayerList{})
	return err
}

// Patch applies the patch and returns the patched phpAppLayer.
func (c *FakePhpAppLayers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PhpAppLayer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(phpapplayersResource, c.ns, name, pt, data, subresources...), &v1alpha1.PhpAppLayer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PhpAppLayer), err
}
