/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}

// ProjectNamespaceListerExpansion allows custom methods to be added to
// ProjectNamespaceLister.
type ProjectNamespaceListerExpansion interface{}

// ReportGroupListerExpansion allows custom methods to be added to
// ReportGroupLister.
type ReportGroupListerExpansion interface{}

// ReportGroupNamespaceListerExpansion allows custom methods to be added to
// ReportGroupNamespaceLister.
type ReportGroupNamespaceListerExpansion interface{}

// ResourcePolicyListerExpansion allows custom methods to be added to
// ResourcePolicyLister.
type ResourcePolicyListerExpansion interface{}

// ResourcePolicyNamespaceListerExpansion allows custom methods to be added to
// ResourcePolicyNamespaceLister.
type ResourcePolicyNamespaceListerExpansion interface{}

// SourceCredentialListerExpansion allows custom methods to be added to
// SourceCredentialLister.
type SourceCredentialListerExpansion interface{}

// SourceCredentialNamespaceListerExpansion allows custom methods to be added to
// SourceCredentialNamespaceLister.
type SourceCredentialNamespaceListerExpansion interface{}

// WebhookListerExpansion allows custom methods to be added to
// WebhookLister.
type WebhookListerExpansion interface{}

// WebhookNamespaceListerExpansion allows custom methods to be added to
// WebhookNamespaceLister.
type WebhookNamespaceListerExpansion interface{}
