/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/db/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProxyTargets implements ProxyTargetInterface
type FakeProxyTargets struct {
	Fake *FakeDbV1alpha1
	ns   string
}

var proxytargetsResource = schema.GroupVersionResource{Group: "db.aws.kubeform.com", Version: "v1alpha1", Resource: "proxytargets"}

var proxytargetsKind = schema.GroupVersionKind{Group: "db.aws.kubeform.com", Version: "v1alpha1", Kind: "ProxyTarget"}

// Get takes name of the proxyTarget, and returns the corresponding proxyTarget object, and an error if there is any.
func (c *FakeProxyTargets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProxyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(proxytargetsResource, c.ns, name), &v1alpha1.ProxyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyTarget), err
}

// List takes label and field selectors, and returns the list of ProxyTargets that match those selectors.
func (c *FakeProxyTargets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProxyTargetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(proxytargetsResource, proxytargetsKind, c.ns, opts), &v1alpha1.ProxyTargetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProxyTargetList{ListMeta: obj.(*v1alpha1.ProxyTargetList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProxyTargetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested proxyTargets.
func (c *FakeProxyTargets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(proxytargetsResource, c.ns, opts))

}

// Create takes the representation of a proxyTarget and creates it.  Returns the server's representation of the proxyTarget, and an error, if there is any.
func (c *FakeProxyTargets) Create(ctx context.Context, proxyTarget *v1alpha1.ProxyTarget, opts v1.CreateOptions) (result *v1alpha1.ProxyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(proxytargetsResource, c.ns, proxyTarget), &v1alpha1.ProxyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyTarget), err
}

// Update takes the representation of a proxyTarget and updates it. Returns the server's representation of the proxyTarget, and an error, if there is any.
func (c *FakeProxyTargets) Update(ctx context.Context, proxyTarget *v1alpha1.ProxyTarget, opts v1.UpdateOptions) (result *v1alpha1.ProxyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(proxytargetsResource, c.ns, proxyTarget), &v1alpha1.ProxyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyTarget), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProxyTargets) UpdateStatus(ctx context.Context, proxyTarget *v1alpha1.ProxyTarget, opts v1.UpdateOptions) (*v1alpha1.ProxyTarget, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(proxytargetsResource, "status", c.ns, proxyTarget), &v1alpha1.ProxyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyTarget), err
}

// Delete takes name of the proxyTarget and deletes it. Returns an error if one occurs.
func (c *FakeProxyTargets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(proxytargetsResource, c.ns, name), &v1alpha1.ProxyTarget{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProxyTargets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(proxytargetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProxyTargetList{})
	return err
}

// Patch applies the patch and returns the patched proxyTarget.
func (c *FakeProxyTargets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProxyTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(proxytargetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProxyTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyTarget), err
}
