/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ComponentListerExpansion allows custom methods to be added to
// ComponentLister.
type ComponentListerExpansion interface{}

// ComponentNamespaceListerExpansion allows custom methods to be added to
// ComponentNamespaceLister.
type ComponentNamespaceListerExpansion interface{}

// DistributionConfigurationListerExpansion allows custom methods to be added to
// DistributionConfigurationLister.
type DistributionConfigurationListerExpansion interface{}

// DistributionConfigurationNamespaceListerExpansion allows custom methods to be added to
// DistributionConfigurationNamespaceLister.
type DistributionConfigurationNamespaceListerExpansion interface{}

// ImageListerExpansion allows custom methods to be added to
// ImageLister.
type ImageListerExpansion interface{}

// ImageNamespaceListerExpansion allows custom methods to be added to
// ImageNamespaceLister.
type ImageNamespaceListerExpansion interface{}

// ImagePipelineListerExpansion allows custom methods to be added to
// ImagePipelineLister.
type ImagePipelineListerExpansion interface{}

// ImagePipelineNamespaceListerExpansion allows custom methods to be added to
// ImagePipelineNamespaceLister.
type ImagePipelineNamespaceListerExpansion interface{}

// ImageRecipeListerExpansion allows custom methods to be added to
// ImageRecipeLister.
type ImageRecipeListerExpansion interface{}

// ImageRecipeNamespaceListerExpansion allows custom methods to be added to
// ImageRecipeNamespaceLister.
type ImageRecipeNamespaceListerExpansion interface{}

// InfrastructureConfigurationListerExpansion allows custom methods to be added to
// InfrastructureConfigurationLister.
type InfrastructureConfigurationListerExpansion interface{}

// InfrastructureConfigurationNamespaceListerExpansion allows custom methods to be added to
// InfrastructureConfigurationNamespaceLister.
type InfrastructureConfigurationNamespaceListerExpansion interface{}
