/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/apprunner/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomDomainAssociations implements CustomDomainAssociationInterface
type FakeCustomDomainAssociations struct {
	Fake *FakeApprunnerV1alpha1
	ns   string
}

var customdomainassociationsResource = schema.GroupVersionResource{Group: "apprunner.aws.kubeform.com", Version: "v1alpha1", Resource: "customdomainassociations"}

var customdomainassociationsKind = schema.GroupVersionKind{Group: "apprunner.aws.kubeform.com", Version: "v1alpha1", Kind: "CustomDomainAssociation"}

// Get takes name of the customDomainAssociation, and returns the corresponding customDomainAssociation object, and an error if there is any.
func (c *FakeCustomDomainAssociations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomDomainAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customdomainassociationsResource, c.ns, name), &v1alpha1.CustomDomainAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomDomainAssociation), err
}

// List takes label and field selectors, and returns the list of CustomDomainAssociations that match those selectors.
func (c *FakeCustomDomainAssociations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomDomainAssociationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customdomainassociationsResource, customdomainassociationsKind, c.ns, opts), &v1alpha1.CustomDomainAssociationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomDomainAssociationList{ListMeta: obj.(*v1alpha1.CustomDomainAssociationList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomDomainAssociationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customDomainAssociations.
func (c *FakeCustomDomainAssociations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customdomainassociationsResource, c.ns, opts))

}

// Create takes the representation of a customDomainAssociation and creates it.  Returns the server's representation of the customDomainAssociation, and an error, if there is any.
func (c *FakeCustomDomainAssociations) Create(ctx context.Context, customDomainAssociation *v1alpha1.CustomDomainAssociation, opts v1.CreateOptions) (result *v1alpha1.CustomDomainAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customdomainassociationsResource, c.ns, customDomainAssociation), &v1alpha1.CustomDomainAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomDomainAssociation), err
}

// Update takes the representation of a customDomainAssociation and updates it. Returns the server's representation of the customDomainAssociation, and an error, if there is any.
func (c *FakeCustomDomainAssociations) Update(ctx context.Context, customDomainAssociation *v1alpha1.CustomDomainAssociation, opts v1.UpdateOptions) (result *v1alpha1.CustomDomainAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customdomainassociationsResource, c.ns, customDomainAssociation), &v1alpha1.CustomDomainAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomDomainAssociation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomDomainAssociations) UpdateStatus(ctx context.Context, customDomainAssociation *v1alpha1.CustomDomainAssociation, opts v1.UpdateOptions) (*v1alpha1.CustomDomainAssociation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(customdomainassociationsResource, "status", c.ns, customDomainAssociation), &v1alpha1.CustomDomainAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomDomainAssociation), err
}

// Delete takes name of the customDomainAssociation and deletes it. Returns an error if one occurs.
func (c *FakeCustomDomainAssociations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customdomainassociationsResource, c.ns, name), &v1alpha1.CustomDomainAssociation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomDomainAssociations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customdomainassociationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomDomainAssociationList{})
	return err
}

// Patch applies the patch and returns the patched customDomainAssociation.
func (c *FakeCustomDomainAssociations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomDomainAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customdomainassociationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomDomainAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomDomainAssociation), err
}
