/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-aws-api/apis/glue/v1alpha1"
)

// FakeCatalogDatabases implements CatalogDatabaseInterface
type FakeCatalogDatabases struct {
	Fake *FakeGlueV1alpha1
	ns   string
}

var catalogdatabasesResource = schema.GroupVersionResource{Group: "glue.aws.kubeform.com", Version: "v1alpha1", Resource: "catalogdatabases"}

var catalogdatabasesKind = schema.GroupVersionKind{Group: "glue.aws.kubeform.com", Version: "v1alpha1", Kind: "CatalogDatabase"}

// Get takes name of the catalogDatabase, and returns the corresponding catalogDatabase object, and an error if there is any.
func (c *FakeCatalogDatabases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CatalogDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(catalogdatabasesResource, c.ns, name), &v1alpha1.CatalogDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogDatabase), err
}

// List takes label and field selectors, and returns the list of CatalogDatabases that match those selectors.
func (c *FakeCatalogDatabases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CatalogDatabaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(catalogdatabasesResource, catalogdatabasesKind, c.ns, opts), &v1alpha1.CatalogDatabaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CatalogDatabaseList{ListMeta: obj.(*v1alpha1.CatalogDatabaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.CatalogDatabaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested catalogDatabases.
func (c *FakeCatalogDatabases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(catalogdatabasesResource, c.ns, opts))

}

// Create takes the representation of a catalogDatabase and creates it.  Returns the server's representation of the catalogDatabase, and an error, if there is any.
func (c *FakeCatalogDatabases) Create(ctx context.Context, catalogDatabase *v1alpha1.CatalogDatabase, opts v1.CreateOptions) (result *v1alpha1.CatalogDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(catalogdatabasesResource, c.ns, catalogDatabase), &v1alpha1.CatalogDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogDatabase), err
}

// Update takes the representation of a catalogDatabase and updates it. Returns the server's representation of the catalogDatabase, and an error, if there is any.
func (c *FakeCatalogDatabases) Update(ctx context.Context, catalogDatabase *v1alpha1.CatalogDatabase, opts v1.UpdateOptions) (result *v1alpha1.CatalogDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(catalogdatabasesResource, c.ns, catalogDatabase), &v1alpha1.CatalogDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogDatabase), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCatalogDatabases) UpdateStatus(ctx context.Context, catalogDatabase *v1alpha1.CatalogDatabase, opts v1.UpdateOptions) (*v1alpha1.CatalogDatabase, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(catalogdatabasesResource, "status", c.ns, catalogDatabase), &v1alpha1.CatalogDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogDatabase), err
}

// Delete takes name of the catalogDatabase and deletes it. Returns an error if one occurs.
func (c *FakeCatalogDatabases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(catalogdatabasesResource, c.ns, name), &v1alpha1.CatalogDatabase{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCatalogDatabases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(catalogdatabasesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CatalogDatabaseList{})
	return err
}

// Patch applies the patch and returns the patched catalogDatabase.
func (c *FakeCatalogDatabases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CatalogDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(catalogdatabasesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CatalogDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CatalogDatabase), err
}
