/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/glue/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMlTransforms implements MlTransformInterface
type FakeMlTransforms struct {
	Fake *FakeGlueV1alpha1
	ns   string
}

var mltransformsResource = schema.GroupVersionResource{Group: "glue.aws.kubeform.com", Version: "v1alpha1", Resource: "mltransforms"}

var mltransformsKind = schema.GroupVersionKind{Group: "glue.aws.kubeform.com", Version: "v1alpha1", Kind: "MlTransform"}

// Get takes name of the mlTransform, and returns the corresponding mlTransform object, and an error if there is any.
func (c *FakeMlTransforms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MlTransform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mltransformsResource, c.ns, name), &v1alpha1.MlTransform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MlTransform), err
}

// List takes label and field selectors, and returns the list of MlTransforms that match those selectors.
func (c *FakeMlTransforms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MlTransformList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mltransformsResource, mltransformsKind, c.ns, opts), &v1alpha1.MlTransformList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MlTransformList{ListMeta: obj.(*v1alpha1.MlTransformList).ListMeta}
	for _, item := range obj.(*v1alpha1.MlTransformList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mlTransforms.
func (c *FakeMlTransforms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mltransformsResource, c.ns, opts))

}

// Create takes the representation of a mlTransform and creates it.  Returns the server's representation of the mlTransform, and an error, if there is any.
func (c *FakeMlTransforms) Create(ctx context.Context, mlTransform *v1alpha1.MlTransform, opts v1.CreateOptions) (result *v1alpha1.MlTransform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mltransformsResource, c.ns, mlTransform), &v1alpha1.MlTransform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MlTransform), err
}

// Update takes the representation of a mlTransform and updates it. Returns the server's representation of the mlTransform, and an error, if there is any.
func (c *FakeMlTransforms) Update(ctx context.Context, mlTransform *v1alpha1.MlTransform, opts v1.UpdateOptions) (result *v1alpha1.MlTransform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mltransformsResource, c.ns, mlTransform), &v1alpha1.MlTransform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MlTransform), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMlTransforms) UpdateStatus(ctx context.Context, mlTransform *v1alpha1.MlTransform, opts v1.UpdateOptions) (*v1alpha1.MlTransform, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mltransformsResource, "status", c.ns, mlTransform), &v1alpha1.MlTransform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MlTransform), err
}

// Delete takes name of the mlTransform and deletes it. Returns an error if one occurs.
func (c *FakeMlTransforms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mltransformsResource, c.ns, name), &v1alpha1.MlTransform{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMlTransforms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mltransformsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MlTransformList{})
	return err
}

// Patch applies the patch and returns the patched mlTransform.
func (c *FakeMlTransforms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MlTransform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mltransformsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MlTransform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MlTransform), err
}
