apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: aws.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: taskdefinitions.ecs.aws.kubeform.com
spec:
  group: ecs.aws.kubeform.com
  names:
    kind: TaskDefinition
    listKind: TaskDefinitionList
    plural: taskdefinitions
    singular: taskdefinition
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  arn:
                    type: string
                  containerDefinitions:
                    type: string
                  cpu:
                    type: string
                  ephemeralStorage:
                    properties:
                      sizeInGib:
                        format: int64
                        type: integer
                    required:
                    - sizeInGib
                    type: object
                  executionRoleArn:
                    type: string
                  family:
                    type: string
                  id:
                    type: string
                  inferenceAccelerator:
                    items:
                      properties:
                        deviceName:
                          type: string
                        deviceType:
                          type: string
                      required:
                      - deviceName
                      - deviceType
                      type: object
                    type: array
                  ipcMode:
                    type: string
                  memory:
                    type: string
                  networkMode:
                    type: string
                  pidMode:
                    type: string
                  placementConstraints:
                    items:
                      properties:
                        expression:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    maxItems: 10
                    type: array
                  proxyConfiguration:
                    properties:
                      containerName:
                        type: string
                      properties:
                        additionalProperties:
                          type: string
                        type: object
                      type:
                        type: string
                    required:
                    - containerName
                    type: object
                  requiresCompatibilities:
                    items:
                      type: string
                    type: array
                  revision:
                    format: int64
                    type: integer
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tagsAll:
                    additionalProperties:
                      type: string
                    type: object
                  taskRoleArn:
                    type: string
                  volume:
                    items:
                      properties:
                        dockerVolumeConfiguration:
                          properties:
                            autoprovision:
                              type: boolean
                            driver:
                              type: string
                            driverOpts:
                              additionalProperties:
                                type: string
                              type: object
                            labels:
                              additionalProperties:
                                type: string
                              type: object
                            scope:
                              type: string
                          type: object
                        efsVolumeConfiguration:
                          properties:
                            authorizationConfig:
                              properties:
                                accessPointID:
                                  type: string
                                iam:
                                  type: string
                              type: object
                            fileSystemID:
                              type: string
                            rootDirectory:
                              type: string
                            transitEncryption:
                              type: string
                            transitEncryptionPort:
                              format: int64
                              type: integer
                          required:
                          - fileSystemID
                          type: object
                        fsxWindowsFileServerVolumeConfiguration:
                          properties:
                            authorizationConfig:
                              properties:
                                credentialsParameter:
                                  type: string
                                domain:
                                  type: string
                              required:
                              - credentialsParameter
                              - domain
                              type: object
                            fileSystemID:
                              type: string
                            rootDirectory:
                              type: string
                          required:
                          - authorizationConfig
                          - fileSystemID
                          - rootDirectory
                          type: object
                        hostPath:
                          type: string
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                required:
                - containerDefinitions
                - family
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  arn:
                    type: string
                  containerDefinitions:
                    type: string
                  cpu:
                    type: string
                  ephemeralStorage:
                    properties:
                      sizeInGib:
                        format: int64
                        type: integer
                    required:
                    - sizeInGib
                    type: object
                  executionRoleArn:
                    type: string
                  family:
                    type: string
                  id:
                    type: string
                  inferenceAccelerator:
                    items:
                      properties:
                        deviceName:
                          type: string
                        deviceType:
                          type: string
                      required:
                      - deviceName
                      - deviceType
                      type: object
                    type: array
                  ipcMode:
                    type: string
                  memory:
                    type: string
                  networkMode:
                    type: string
                  pidMode:
                    type: string
                  placementConstraints:
                    items:
                      properties:
                        expression:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    maxItems: 10
                    type: array
                  proxyConfiguration:
                    properties:
                      containerName:
                        type: string
                      properties:
                        additionalProperties:
                          type: string
                        type: object
                      type:
                        type: string
                    required:
                    - containerName
                    type: object
                  requiresCompatibilities:
                    items:
                      type: string
                    type: array
                  revision:
                    format: int64
                    type: integer
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tagsAll:
                    additionalProperties:
                      type: string
                    type: object
                  taskRoleArn:
                    type: string
                  volume:
                    items:
                      properties:
                        dockerVolumeConfiguration:
                          properties:
                            autoprovision:
                              type: boolean
                            driver:
                              type: string
                            driverOpts:
                              additionalProperties:
                                type: string
                              type: object
                            labels:
                              additionalProperties:
                                type: string
                              type: object
                            scope:
                              type: string
                          type: object
                        efsVolumeConfiguration:
                          properties:
                            authorizationConfig:
                              properties:
                                accessPointID:
                                  type: string
                                iam:
                                  type: string
                              type: object
                            fileSystemID:
                              type: string
                            rootDirectory:
                              type: string
                            transitEncryption:
                              type: string
                            transitEncryptionPort:
                              format: int64
                              type: integer
                          required:
                          - fileSystemID
                          type: object
                        fsxWindowsFileServerVolumeConfiguration:
                          properties:
                            authorizationConfig:
                              properties:
                                credentialsParameter:
                                  type: string
                                domain:
                                  type: string
                              required:
                              - credentialsParameter
                              - domain
                              type: object
                            fileSystemID:
                              type: string
                            rootDirectory:
                              type: string
                          required:
                          - authorizationConfig
                          - fileSystemID
                          - rootDirectory
                          type: object
                        hostPath:
                          type: string
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                required:
                - containerDefinitions
                - family
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
