apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: aws.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: services.ecs.aws.kubeform.com
spec:
  group: ecs.aws.kubeform.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  capacityProviderStrategy:
                    items:
                      properties:
                        base:
                          format: int64
                          type: integer
                        capacityProvider:
                          type: string
                        weight:
                          format: int64
                          type: integer
                      required:
                      - capacityProvider
                      type: object
                    type: array
                  cluster:
                    type: string
                  deploymentCircuitBreaker:
                    properties:
                      enable:
                        type: boolean
                      rollback:
                        type: boolean
                    required:
                    - enable
                    - rollback
                    type: object
                  deploymentController:
                    properties:
                      type:
                        type: string
                    type: object
                  deploymentMaximumPercent:
                    format: int64
                    type: integer
                  deploymentMinimumHealthyPercent:
                    format: int64
                    type: integer
                  desiredCount:
                    format: int64
                    type: integer
                  enableEcsManagedTags:
                    type: boolean
                  enableExecuteCommand:
                    type: boolean
                  forceNewDeployment:
                    type: boolean
                  healthCheckGracePeriodSeconds:
                    format: int64
                    type: integer
                  iamRole:
                    type: string
                  id:
                    type: string
                  launchType:
                    type: string
                  loadBalancer:
                    items:
                      properties:
                        containerName:
                          type: string
                        containerPort:
                          format: int64
                          type: integer
                        elbName:
                          type: string
                        targetGroupArn:
                          type: string
                      required:
                      - containerName
                      - containerPort
                      type: object
                    type: array
                  name:
                    type: string
                  networkConfiguration:
                    properties:
                      assignPublicIP:
                        type: boolean
                      securityGroups:
                        items:
                          type: string
                        type: array
                      subnets:
                        items:
                          type: string
                        type: array
                    required:
                    - subnets
                    type: object
                  orderedPlacementStrategy:
                    items:
                      properties:
                        field:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    maxItems: 5
                    type: array
                  placementConstraints:
                    items:
                      properties:
                        expression:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    maxItems: 10
                    type: array
                  platformVersion:
                    type: string
                  propagateTags:
                    type: string
                  schedulingStrategy:
                    type: string
                  serviceRegistries:
                    properties:
                      containerName:
                        type: string
                      containerPort:
                        format: int64
                        type: integer
                      port:
                        format: int64
                        type: integer
                      registryArn:
                        type: string
                    required:
                    - registryArn
                    type: object
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tagsAll:
                    additionalProperties:
                      type: string
                    type: object
                  taskDefinition:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  waitForSteadyState:
                    type: boolean
                required:
                - name
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  capacityProviderStrategy:
                    items:
                      properties:
                        base:
                          format: int64
                          type: integer
                        capacityProvider:
                          type: string
                        weight:
                          format: int64
                          type: integer
                      required:
                      - capacityProvider
                      type: object
                    type: array
                  cluster:
                    type: string
                  deploymentCircuitBreaker:
                    properties:
                      enable:
                        type: boolean
                      rollback:
                        type: boolean
                    required:
                    - enable
                    - rollback
                    type: object
                  deploymentController:
                    properties:
                      type:
                        type: string
                    type: object
                  deploymentMaximumPercent:
                    format: int64
                    type: integer
                  deploymentMinimumHealthyPercent:
                    format: int64
                    type: integer
                  desiredCount:
                    format: int64
                    type: integer
                  enableEcsManagedTags:
                    type: boolean
                  enableExecuteCommand:
                    type: boolean
                  forceNewDeployment:
                    type: boolean
                  healthCheckGracePeriodSeconds:
                    format: int64
                    type: integer
                  iamRole:
                    type: string
                  id:
                    type: string
                  launchType:
                    type: string
                  loadBalancer:
                    items:
                      properties:
                        containerName:
                          type: string
                        containerPort:
                          format: int64
                          type: integer
                        elbName:
                          type: string
                        targetGroupArn:
                          type: string
                      required:
                      - containerName
                      - containerPort
                      type: object
                    type: array
                  name:
                    type: string
                  networkConfiguration:
                    properties:
                      assignPublicIP:
                        type: boolean
                      securityGroups:
                        items:
                          type: string
                        type: array
                      subnets:
                        items:
                          type: string
                        type: array
                    required:
                    - subnets
                    type: object
                  orderedPlacementStrategy:
                    items:
                      properties:
                        field:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    maxItems: 5
                    type: array
                  placementConstraints:
                    items:
                      properties:
                        expression:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    maxItems: 10
                    type: array
                  platformVersion:
                    type: string
                  propagateTags:
                    type: string
                  schedulingStrategy:
                    type: string
                  serviceRegistries:
                    properties:
                      containerName:
                        type: string
                      containerPort:
                        format: int64
                        type: integer
                      port:
                        format: int64
                        type: integer
                      registryArn:
                        type: string
                    required:
                    - registryArn
                    type: object
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tagsAll:
                    additionalProperties:
                      type: string
                    type: object
                  taskDefinition:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  waitForSteadyState:
                    type: boolean
                required:
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
