apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: aws.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: domains.sagemaker.aws.kubeform.com
spec:
  group: sagemaker.aws.kubeform.com
  names:
    kind: Domain
    listKind: DomainList
    plural: domains
    singular: domain
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  appNetworkAccessType:
                    type: string
                  arn:
                    type: string
                  authMode:
                    type: string
                  defaultUserSettings:
                    properties:
                      executionRole:
                        type: string
                      jupyterServerAppSettings:
                        properties:
                          defaultResourceSpec:
                            properties:
                              instanceType:
                                type: string
                              sagemakerImageArn:
                                type: string
                            type: object
                        type: object
                      kernelGatewayAppSettings:
                        properties:
                          customImage:
                            items:
                              properties:
                                appImageConfigName:
                                  type: string
                                imageName:
                                  type: string
                                imageVersionNumber:
                                  format: int64
                                  type: integer
                              required:
                              - appImageConfigName
                              - imageName
                              type: object
                            maxItems: 30
                            type: array
                          defaultResourceSpec:
                            properties:
                              instanceType:
                                type: string
                              sagemakerImageArn:
                                type: string
                            type: object
                        type: object
                      securityGroups:
                        items:
                          type: string
                        maxItems: 5
                        type: array
                      sharingSettings:
                        properties:
                          notebookOutputOption:
                            type: string
                          s3KmsKeyID:
                            type: string
                          s3OutputPath:
                            type: string
                        type: object
                      tensorBoardAppSettings:
                        properties:
                          defaultResourceSpec:
                            properties:
                              instanceType:
                                type: string
                              sagemakerImageArn:
                                type: string
                            type: object
                        type: object
                    required:
                    - executionRole
                    type: object
                  domainName:
                    type: string
                  homeEfsFileSystemID:
                    type: string
                  id:
                    type: string
                  kmsKeyID:
                    type: string
                  singleSignOnManagedApplicationInstanceID:
                    type: string
                  subnetIDS:
                    items:
                      type: string
                    maxItems: 16
                    type: array
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tagsAll:
                    additionalProperties:
                      type: string
                    type: object
                  url:
                    type: string
                  vpcID:
                    type: string
                required:
                - authMode
                - defaultUserSettings
                - domainName
                - subnetIDS
                - vpcID
                type: object
              state:
                properties:
                  appNetworkAccessType:
                    type: string
                  arn:
                    type: string
                  authMode:
                    type: string
                  defaultUserSettings:
                    properties:
                      executionRole:
                        type: string
                      jupyterServerAppSettings:
                        properties:
                          defaultResourceSpec:
                            properties:
                              instanceType:
                                type: string
                              sagemakerImageArn:
                                type: string
                            type: object
                        type: object
                      kernelGatewayAppSettings:
                        properties:
                          customImage:
                            items:
                              properties:
                                appImageConfigName:
                                  type: string
                                imageName:
                                  type: string
                                imageVersionNumber:
                                  format: int64
                                  type: integer
                              required:
                              - appImageConfigName
                              - imageName
                              type: object
                            maxItems: 30
                            type: array
                          defaultResourceSpec:
                            properties:
                              instanceType:
                                type: string
                              sagemakerImageArn:
                                type: string
                            type: object
                        type: object
                      securityGroups:
                        items:
                          type: string
                        maxItems: 5
                        type: array
                      sharingSettings:
                        properties:
                          notebookOutputOption:
                            type: string
                          s3KmsKeyID:
                            type: string
                          s3OutputPath:
                            type: string
                        type: object
                      tensorBoardAppSettings:
                        properties:
                          defaultResourceSpec:
                            properties:
                              instanceType:
                                type: string
                              sagemakerImageArn:
                                type: string
                            type: object
                        type: object
                    required:
                    - executionRole
                    type: object
                  domainName:
                    type: string
                  homeEfsFileSystemID:
                    type: string
                  id:
                    type: string
                  kmsKeyID:
                    type: string
                  singleSignOnManagedApplicationInstanceID:
                    type: string
                  subnetIDS:
                    items:
                      type: string
                    maxItems: 16
                    type: array
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tagsAll:
                    additionalProperties:
                      type: string
                    type: object
                  url:
                    type: string
                  vpcID:
                    type: string
                required:
                - authMode
                - defaultUserSettings
                - domainName
                - subnetIDS
                - vpcID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
