/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/cloudwatch/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLogMetricFilters implements LogMetricFilterInterface
type FakeLogMetricFilters struct {
	Fake *FakeCloudwatchV1alpha1
	ns   string
}

var logmetricfiltersResource = schema.GroupVersionResource{Group: "cloudwatch.aws.kubeform.com", Version: "v1alpha1", Resource: "logmetricfilters"}

var logmetricfiltersKind = schema.GroupVersionKind{Group: "cloudwatch.aws.kubeform.com", Version: "v1alpha1", Kind: "LogMetricFilter"}

// Get takes name of the logMetricFilter, and returns the corresponding logMetricFilter object, and an error if there is any.
func (c *FakeLogMetricFilters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LogMetricFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(logmetricfiltersResource, c.ns, name), &v1alpha1.LogMetricFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogMetricFilter), err
}

// List takes label and field selectors, and returns the list of LogMetricFilters that match those selectors.
func (c *FakeLogMetricFilters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LogMetricFilterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(logmetricfiltersResource, logmetricfiltersKind, c.ns, opts), &v1alpha1.LogMetricFilterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LogMetricFilterList{ListMeta: obj.(*v1alpha1.LogMetricFilterList).ListMeta}
	for _, item := range obj.(*v1alpha1.LogMetricFilterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested logMetricFilters.
func (c *FakeLogMetricFilters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(logmetricfiltersResource, c.ns, opts))

}

// Create takes the representation of a logMetricFilter and creates it.  Returns the server's representation of the logMetricFilter, and an error, if there is any.
func (c *FakeLogMetricFilters) Create(ctx context.Context, logMetricFilter *v1alpha1.LogMetricFilter, opts v1.CreateOptions) (result *v1alpha1.LogMetricFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(logmetricfiltersResource, c.ns, logMetricFilter), &v1alpha1.LogMetricFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogMetricFilter), err
}

// Update takes the representation of a logMetricFilter and updates it. Returns the server's representation of the logMetricFilter, and an error, if there is any.
func (c *FakeLogMetricFilters) Update(ctx context.Context, logMetricFilter *v1alpha1.LogMetricFilter, opts v1.UpdateOptions) (result *v1alpha1.LogMetricFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(logmetricfiltersResource, c.ns, logMetricFilter), &v1alpha1.LogMetricFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogMetricFilter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLogMetricFilters) UpdateStatus(ctx context.Context, logMetricFilter *v1alpha1.LogMetricFilter, opts v1.UpdateOptions) (*v1alpha1.LogMetricFilter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(logmetricfiltersResource, "status", c.ns, logMetricFilter), &v1alpha1.LogMetricFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogMetricFilter), err
}

// Delete takes name of the logMetricFilter and deletes it. Returns an error if one occurs.
func (c *FakeLogMetricFilters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(logmetricfiltersResource, c.ns, name), &v1alpha1.LogMetricFilter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLogMetricFilters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(logmetricfiltersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LogMetricFilterList{})
	return err
}

// Patch applies the patch and returns the patched logMetricFilter.
func (c *FakeLogMetricFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LogMetricFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(logmetricfiltersResource, c.ns, name, pt, data, subresources...), &v1alpha1.LogMetricFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogMetricFilter), err
}
