/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-aws-api/apis/pinpoint/v1alpha1"
)

// FakeApnsVoipSandboxChannels implements ApnsVoipSandboxChannelInterface
type FakeApnsVoipSandboxChannels struct {
	Fake *FakePinpointV1alpha1
	ns   string
}

var apnsvoipsandboxchannelsResource = schema.GroupVersionResource{Group: "pinpoint.aws.kubeform.com", Version: "v1alpha1", Resource: "apnsvoipsandboxchannels"}

var apnsvoipsandboxchannelsKind = schema.GroupVersionKind{Group: "pinpoint.aws.kubeform.com", Version: "v1alpha1", Kind: "ApnsVoipSandboxChannel"}

// Get takes name of the apnsVoipSandboxChannel, and returns the corresponding apnsVoipSandboxChannel object, and an error if there is any.
func (c *FakeApnsVoipSandboxChannels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ApnsVoipSandboxChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apnsvoipsandboxchannelsResource, c.ns, name), &v1alpha1.ApnsVoipSandboxChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApnsVoipSandboxChannel), err
}

// List takes label and field selectors, and returns the list of ApnsVoipSandboxChannels that match those selectors.
func (c *FakeApnsVoipSandboxChannels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApnsVoipSandboxChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apnsvoipsandboxchannelsResource, apnsvoipsandboxchannelsKind, c.ns, opts), &v1alpha1.ApnsVoipSandboxChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ApnsVoipSandboxChannelList{ListMeta: obj.(*v1alpha1.ApnsVoipSandboxChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.ApnsVoipSandboxChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apnsVoipSandboxChannels.
func (c *FakeApnsVoipSandboxChannels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apnsvoipsandboxchannelsResource, c.ns, opts))

}

// Create takes the representation of a apnsVoipSandboxChannel and creates it.  Returns the server's representation of the apnsVoipSandboxChannel, and an error, if there is any.
func (c *FakeApnsVoipSandboxChannels) Create(ctx context.Context, apnsVoipSandboxChannel *v1alpha1.ApnsVoipSandboxChannel, opts v1.CreateOptions) (result *v1alpha1.ApnsVoipSandboxChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apnsvoipsandboxchannelsResource, c.ns, apnsVoipSandboxChannel), &v1alpha1.ApnsVoipSandboxChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApnsVoipSandboxChannel), err
}

// Update takes the representation of a apnsVoipSandboxChannel and updates it. Returns the server's representation of the apnsVoipSandboxChannel, and an error, if there is any.
func (c *FakeApnsVoipSandboxChannels) Update(ctx context.Context, apnsVoipSandboxChannel *v1alpha1.ApnsVoipSandboxChannel, opts v1.UpdateOptions) (result *v1alpha1.ApnsVoipSandboxChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apnsvoipsandboxchannelsResource, c.ns, apnsVoipSandboxChannel), &v1alpha1.ApnsVoipSandboxChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApnsVoipSandboxChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeApnsVoipSandboxChannels) UpdateStatus(ctx context.Context, apnsVoipSandboxChannel *v1alpha1.ApnsVoipSandboxChannel, opts v1.UpdateOptions) (*v1alpha1.ApnsVoipSandboxChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apnsvoipsandboxchannelsResource, "status", c.ns, apnsVoipSandboxChannel), &v1alpha1.ApnsVoipSandboxChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApnsVoipSandboxChannel), err
}

// Delete takes name of the apnsVoipSandboxChannel and deletes it. Returns an error if one occurs.
func (c *FakeApnsVoipSandboxChannels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(apnsvoipsandboxchannelsResource, c.ns, name), &v1alpha1.ApnsVoipSandboxChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApnsVoipSandboxChannels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apnsvoipsandboxchannelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ApnsVoipSandboxChannelList{})
	return err
}

// Patch applies the patch and returns the patched apnsVoipSandboxChannel.
func (c *FakeApnsVoipSandboxChannels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApnsVoipSandboxChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apnsvoipsandboxchannelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ApnsVoipSandboxChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApnsVoipSandboxChannel), err
}
