/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/route53domains/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRegisteredDomains implements RegisteredDomainInterface
type FakeRegisteredDomains struct {
	Fake *FakeRoute53domainsV1alpha1
	ns   string
}

var registereddomainsResource = schema.GroupVersionResource{Group: "route53domains.aws.kubeform.com", Version: "v1alpha1", Resource: "registereddomains"}

var registereddomainsKind = schema.GroupVersionKind{Group: "route53domains.aws.kubeform.com", Version: "v1alpha1", Kind: "RegisteredDomain"}

// Get takes name of the registeredDomain, and returns the corresponding registeredDomain object, and an error if there is any.
func (c *FakeRegisteredDomains) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RegisteredDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(registereddomainsResource, c.ns, name), &v1alpha1.RegisteredDomain{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegisteredDomain), err
}

// List takes label and field selectors, and returns the list of RegisteredDomains that match those selectors.
func (c *FakeRegisteredDomains) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RegisteredDomainList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(registereddomainsResource, registereddomainsKind, c.ns, opts), &v1alpha1.RegisteredDomainList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RegisteredDomainList{ListMeta: obj.(*v1alpha1.RegisteredDomainList).ListMeta}
	for _, item := range obj.(*v1alpha1.RegisteredDomainList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested registeredDomains.
func (c *FakeRegisteredDomains) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(registereddomainsResource, c.ns, opts))

}

// Create takes the representation of a registeredDomain and creates it.  Returns the server's representation of the registeredDomain, and an error, if there is any.
func (c *FakeRegisteredDomains) Create(ctx context.Context, registeredDomain *v1alpha1.RegisteredDomain, opts v1.CreateOptions) (result *v1alpha1.RegisteredDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(registereddomainsResource, c.ns, registeredDomain), &v1alpha1.RegisteredDomain{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegisteredDomain), err
}

// Update takes the representation of a registeredDomain and updates it. Returns the server's representation of the registeredDomain, and an error, if there is any.
func (c *FakeRegisteredDomains) Update(ctx context.Context, registeredDomain *v1alpha1.RegisteredDomain, opts v1.UpdateOptions) (result *v1alpha1.RegisteredDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(registereddomainsResource, c.ns, registeredDomain), &v1alpha1.RegisteredDomain{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegisteredDomain), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRegisteredDomains) UpdateStatus(ctx context.Context, registeredDomain *v1alpha1.RegisteredDomain, opts v1.UpdateOptions) (*v1alpha1.RegisteredDomain, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(registereddomainsResource, "status", c.ns, registeredDomain), &v1alpha1.RegisteredDomain{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegisteredDomain), err
}

// Delete takes name of the registeredDomain and deletes it. Returns an error if one occurs.
func (c *FakeRegisteredDomains) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(registereddomainsResource, c.ns, name), &v1alpha1.RegisteredDomain{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRegisteredDomains) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(registereddomainsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RegisteredDomainList{})
	return err
}

// Patch applies the patch and returns the patched registeredDomain.
func (c *FakeRegisteredDomains) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RegisteredDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(registereddomainsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RegisteredDomain{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RegisteredDomain), err
}
