/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/provider-aws-api/apis/ssm/v1alpha1"
)

// FakeActivations implements ActivationInterface
type FakeActivations struct {
	Fake *FakeSsmV1alpha1
	ns   string
}

var activationsResource = schema.GroupVersionResource{Group: "ssm.aws.kubeform.com", Version: "v1alpha1", Resource: "activations"}

var activationsKind = schema.GroupVersionKind{Group: "ssm.aws.kubeform.com", Version: "v1alpha1", Kind: "Activation"}

// Get takes name of the activation, and returns the corresponding activation object, and an error if there is any.
func (c *FakeActivations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Activation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(activationsResource, c.ns, name), &v1alpha1.Activation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Activation), err
}

// List takes label and field selectors, and returns the list of Activations that match those selectors.
func (c *FakeActivations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ActivationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(activationsResource, activationsKind, c.ns, opts), &v1alpha1.ActivationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ActivationList{ListMeta: obj.(*v1alpha1.ActivationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ActivationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested activations.
func (c *FakeActivations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(activationsResource, c.ns, opts))

}

// Create takes the representation of a activation and creates it.  Returns the server's representation of the activation, and an error, if there is any.
func (c *FakeActivations) Create(ctx context.Context, activation *v1alpha1.Activation, opts v1.CreateOptions) (result *v1alpha1.Activation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(activationsResource, c.ns, activation), &v1alpha1.Activation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Activation), err
}

// Update takes the representation of a activation and updates it. Returns the server's representation of the activation, and an error, if there is any.
func (c *FakeActivations) Update(ctx context.Context, activation *v1alpha1.Activation, opts v1.UpdateOptions) (result *v1alpha1.Activation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(activationsResource, c.ns, activation), &v1alpha1.Activation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Activation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeActivations) UpdateStatus(ctx context.Context, activation *v1alpha1.Activation, opts v1.UpdateOptions) (*v1alpha1.Activation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(activationsResource, "status", c.ns, activation), &v1alpha1.Activation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Activation), err
}

// Delete takes name of the activation and deletes it. Returns an error if one occurs.
func (c *FakeActivations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(activationsResource, c.ns, name), &v1alpha1.Activation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActivations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(activationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ActivationList{})
	return err
}

// Patch applies the patch and returns the patched activation.
func (c *FakeActivations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Activation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(activationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Activation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Activation), err
}
