/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-aws-api/apis/vpc/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePeeringConnections implements PeeringConnectionInterface
type FakePeeringConnections struct {
	Fake *FakeVpcV1alpha1
	ns   string
}

var peeringconnectionsResource = schema.GroupVersionResource{Group: "vpc.aws.kubeform.com", Version: "v1alpha1", Resource: "peeringconnections"}

var peeringconnectionsKind = schema.GroupVersionKind{Group: "vpc.aws.kubeform.com", Version: "v1alpha1", Kind: "PeeringConnection"}

// Get takes name of the peeringConnection, and returns the corresponding peeringConnection object, and an error if there is any.
func (c *FakePeeringConnections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PeeringConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(peeringconnectionsResource, c.ns, name), &v1alpha1.PeeringConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PeeringConnection), err
}

// List takes label and field selectors, and returns the list of PeeringConnections that match those selectors.
func (c *FakePeeringConnections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PeeringConnectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(peeringconnectionsResource, peeringconnectionsKind, c.ns, opts), &v1alpha1.PeeringConnectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PeeringConnectionList{ListMeta: obj.(*v1alpha1.PeeringConnectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.PeeringConnectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested peeringConnections.
func (c *FakePeeringConnections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(peeringconnectionsResource, c.ns, opts))

}

// Create takes the representation of a peeringConnection and creates it.  Returns the server's representation of the peeringConnection, and an error, if there is any.
func (c *FakePeeringConnections) Create(ctx context.Context, peeringConnection *v1alpha1.PeeringConnection, opts v1.CreateOptions) (result *v1alpha1.PeeringConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(peeringconnectionsResource, c.ns, peeringConnection), &v1alpha1.PeeringConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PeeringConnection), err
}

// Update takes the representation of a peeringConnection and updates it. Returns the server's representation of the peeringConnection, and an error, if there is any.
func (c *FakePeeringConnections) Update(ctx context.Context, peeringConnection *v1alpha1.PeeringConnection, opts v1.UpdateOptions) (result *v1alpha1.PeeringConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(peeringconnectionsResource, c.ns, peeringConnection), &v1alpha1.PeeringConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PeeringConnection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePeeringConnections) UpdateStatus(ctx context.Context, peeringConnection *v1alpha1.PeeringConnection, opts v1.UpdateOptions) (*v1alpha1.PeeringConnection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(peeringconnectionsResource, "status", c.ns, peeringConnection), &v1alpha1.PeeringConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PeeringConnection), err
}

// Delete takes name of the peeringConnection and deletes it. Returns an error if one occurs.
func (c *FakePeeringConnections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(peeringconnectionsResource, c.ns, name), &v1alpha1.PeeringConnection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePeeringConnections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(peeringconnectionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PeeringConnectionList{})
	return err
}

// Patch applies the patch and returns the patched peeringConnection.
func (c *FakePeeringConnections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PeeringConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(peeringconnectionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PeeringConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PeeringConnection), err
}
