/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VoiceConnectorListerExpansion allows custom methods to be added to
// VoiceConnectorLister.
type VoiceConnectorListerExpansion interface{}

// VoiceConnectorNamespaceListerExpansion allows custom methods to be added to
// VoiceConnectorNamespaceLister.
type VoiceConnectorNamespaceListerExpansion interface{}

// VoiceConnectorGroupListerExpansion allows custom methods to be added to
// VoiceConnectorGroupLister.
type VoiceConnectorGroupListerExpansion interface{}

// VoiceConnectorGroupNamespaceListerExpansion allows custom methods to be added to
// VoiceConnectorGroupNamespaceLister.
type VoiceConnectorGroupNamespaceListerExpansion interface{}

// VoiceConnectorLoggingListerExpansion allows custom methods to be added to
// VoiceConnectorLoggingLister.
type VoiceConnectorLoggingListerExpansion interface{}

// VoiceConnectorLoggingNamespaceListerExpansion allows custom methods to be added to
// VoiceConnectorLoggingNamespaceLister.
type VoiceConnectorLoggingNamespaceListerExpansion interface{}

// VoiceConnectorOriginationListerExpansion allows custom methods to be added to
// VoiceConnectorOriginationLister.
type VoiceConnectorOriginationListerExpansion interface{}

// VoiceConnectorOriginationNamespaceListerExpansion allows custom methods to be added to
// VoiceConnectorOriginationNamespaceLister.
type VoiceConnectorOriginationNamespaceListerExpansion interface{}

// VoiceConnectorStreamingListerExpansion allows custom methods to be added to
// VoiceConnectorStreamingLister.
type VoiceConnectorStreamingListerExpansion interface{}

// VoiceConnectorStreamingNamespaceListerExpansion allows custom methods to be added to
// VoiceConnectorStreamingNamespaceLister.
type VoiceConnectorStreamingNamespaceListerExpansion interface{}

// VoiceConnectorTerminationListerExpansion allows custom methods to be added to
// VoiceConnectorTerminationLister.
type VoiceConnectorTerminationListerExpansion interface{}

// VoiceConnectorTerminationNamespaceListerExpansion allows custom methods to be added to
// VoiceConnectorTerminationNamespaceLister.
type VoiceConnectorTerminationNamespaceListerExpansion interface{}

// VoiceConnectorTerminationCredentialsListerExpansion allows custom methods to be added to
// VoiceConnectorTerminationCredentialsLister.
type VoiceConnectorTerminationCredentialsListerExpansion interface{}

// VoiceConnectorTerminationCredentialsNamespaceListerExpansion allows custom methods to be added to
// VoiceConnectorTerminationCredentialsNamespaceLister.
type VoiceConnectorTerminationCredentialsNamespaceListerExpansion interface{}
